# Generated by Django 3.0.6 on 2020-07-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_manag_app', '0002_auto_20200706_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('Book', 'Book'), ('E-book', 'E-book'), ('DVD', 'DVD'), ('Vinyl', 'Vinyl'), ('Map', 'Map'), ('Painting', 'Painting'), ('Decoration', 'Decoration')], max_length=100, null=True),
        ),
    ]
